---
version: '3'

services:
  web: # Frontend
    build: web
    environment:
      WEB_FOLDER: public # Change this
      API_URL: http://localhost:8080/api/todos # Change this
    ports:
      - 8080:80

  app: # Backend
    build: app
    environment:
      MYSQL_HOST: docker_assign_db_1 # Connect to different database by changing IP
      MYSQL_PORT: 3306
      MONGO_HOST: backend
      MONGO_DB: example
      NODE_PORT: 8080
    ports:
      - 8001
    depends_on:
      - web
      - db

  db: # Database
    build: db
    env_file: vars.env
    # ports:
    #   - 27017:27017
    #   #- 3306:3306
    depends_on:
      - web